# Generated by Django 5.1.7 on 2025-04-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='appointment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='student_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
